
app:
    DBConnections:
        -
            ENV: 新規
            DB_SERVER_PRODUCT: ACCESS_VIA_ODBC
            DB: .\data\keiyaku_shinki.accdb
        -
            ENV: 変更
            DB_SERVER_PRODUCT: ACCESS_VIA_ODBC
            DB: .\data\keiyaku_henkou.accdb


    #データディクショナリのデータ項目一覧をダウンロードし、データ項目だけ抜粋し、UTF-8で保存したもの
    DataDictionaryFilePath: .\data\data_dictionary.csv
    #"XXXX_テーブル一覧.xlsx"から、テーブルの論理名と物理名を抜粋し、UTF-8で保存したもの
    DBTableListFilePath: .\data\db_tables.csv
    #データディクショナリのコード一覧ダウンロードし、データ項目だけ抜粋し、UTF-8で保存したもの
    CodeMasterFilePath: .\data\codemaster.csv
